# Generated by Django 2.1.2 on 2018-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleaverequest',
            name='EmpLeave_Req_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Status',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Type',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Emp_No',
            field=models.AutoField(help_text='Unique Emp no for employee table', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empmgrdept',
            name='Emp_MgrDept_ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='LeaveBal_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Leave_Type',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=10),
        ),
    ]
