# Generated by Django 2.1.1 on 2018-12-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Status',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Type',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Leave_Type',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=10),
        ),
    ]
