# Generated by Django 2.1.1 on 2018-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_No', models.PositiveIntegerField(default=0, help_text='Unique Emp no for employee table', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='employee first name', max_length=14)),
                ('Middle_Name', models.CharField(help_text='employee middle name', max_length=14, null=True)),
                ('Last_Name', models.CharField(help_text='employee last name', max_length=14)),
                ('Birth_Date', models.DateField(help_text='employee birth date')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Street_Address', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Postal_Code', models.PositiveIntegerField(default=0, max_length=6)),
                ('Country', models.CharField(max_length=20)),
                ('Mobile_Number', models.PositiveIntegerField(default=0, max_length=10)),
                ('Email_Address', models.EmailField(max_length=70)),
                ('Hire_Date', models.DateField(help_text='Employee joining date')),
                ('End_Date', models.DateField(help_text='Employee last working date in organization')),
                ('Designation', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=10)),
                ('Nationality', models.CharField(max_length=50)),
                ('Worktype', models.CharField(choices=[('Permanent', 'Permanent'), ('Probationary', 'Probationary'), ('Limited-term', 'Limited-term'), ('Temporary', 'Temporary')], max_length=15)),
                ('IsActive', models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')])),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
