# Generated by Django 2.1.1 on 2018-11-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20181112_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='End_Date',
            field=models.DateField(help_text='Employee last working date in organization', null=True),
        ),
    ]
