# Generated by Django 2.1.1 on 2018-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20181201_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleaverequest',
            name='EmpLeave_Req_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Emp_No',
            field=models.AutoField(help_text='Unique Emp no for employee table', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empmgrdept',
            name='Emp_MgrDept_ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='LeaveBal_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
