# Generated by Django 2.1.1 on 2018-11-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_auto_20181112_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='IsActive',
            field=models.BooleanField(),
        ),
    ]
