# Generated by Django 2.1.1 on 2018-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_auto_20181112_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='IsActive',
            field=models.BooleanField(null=True),
        ),
    ]
