# Generated by Django 2.1.1 on 2018-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_auto_20181112_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Mobile_Number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Postal_Code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
