# Generated by Django 2.1.1 on 2018-11-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_auto_20181112_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Designation',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Permanent', 'Permanent'), ('Probationary', 'Probationary'), ('Limited_term', 'Limited-term'), ('Temporary', 'Temporary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Permanent', 'Permanent'), ('Probationary', 'Probationary'), ('Limited_term', 'Limited-term'), ('Temporary', 'Temporary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Worktype',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR'), ('Permanent', 'Permanent'), ('Probationary', 'Probationary'), ('Limited_term', 'Limited-term'), ('Temporary', 'Temporary')], max_length=15),
        ),
    ]
