# Generated by Django 2.1.1 on 2018-11-12 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_auto_20181112_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLeaveRequest',
            fields=[
                ('EmpLeave_Req_ID', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('Emp_FullName', models.CharField(max_length=50)),
                ('Leave_Type', models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined')], max_length=10)),
                ('Manager_FullName', models.CharField(max_length=50)),
                ('Begin_Date', models.DateField(help_text='Leave begin date')),
                ('End_Date', models.DateField(help_text='Leave end date')),
                ('Requested_Days', models.PositiveIntegerField(default=0, help_text='Total no of requested leave days')),
                ('Leave_Status', models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined')], max_length=10)),
                ('Emp_Comments', models.CharField(max_length=500, null=True)),
                ('Emp_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Employee')),
            ],
        ),
    ]
