# Generated by Django 2.1.1 on 2018-11-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_empleaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleaverequest',
            name='Emp_No',
        ),
        migrations.AddField(
            model_name='empleaverequest',
            name='Emp_No_Leave',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_No_Leave', to='LMS.Employee'),
        ),
        migrations.AddField(
            model_name='empleaverequest',
            name='Manager_Emp_No',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Emp_No', to='LMS.Employee'),
        ),
    ]
