# Generated by Django 2.1.1 on 2018-11-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_auto_20181112_2349'),
    ]

    operations = [
    ]
