# Generated by Django 2.1.1 on 2018-11-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_merge_20181113_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_Type', models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined')], max_length=10)),
                ('Available_Days', models.PositiveIntegerField(default=0, help_text='Remaining/available leave days per employee')),
                ('Allocated_Days', models.PositiveIntegerField(default=0, help_text='No of leave days allocated to a leave type per employee per year')),
                ('Emp_No_LeaveBal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_No_LeaveBal', to='LMS.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleaverequest',
            name='Emp_No_Leave',
        ),
        migrations.AddField(
            model_name='empleaverequest',
            name='Emp_No_LeaveReq',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_No_LeaveReq', to='LMS.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('Emp_No_LeaveBal', 'Leave_Type')},
        ),
    ]
