# Generated by Django 2.1.1 on 2018-11-13 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_auto_20181113_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleaverequest',
            name='Emp_No_LeaveReq',
        ),
        migrations.AddField(
            model_name='empleaverequest',
            name='Emp_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_ID', to='LMS.Employee'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='LeaveBalance_ID',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Emp_No_LeaveBal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
    ]
