# Generated by Django 2.1.1 on 2018-11-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_auto_20181113_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('LeaveBal_ID', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('Leave_Type', models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Military_Leave', 'Military'), ('Pregnancy_Disability_Leave', 'PDL'), ('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined')], max_length=10)),
                ('Available_Days', models.PositiveIntegerField(default=0, help_text='Remaining/available leave days per employee')),
                ('Allocated_Days', models.PositiveIntegerField(default=0, help_text='No of leave days allocated to a leave type per employee per year')),
                ('Emp_No_LeaveBal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Employee')),
            ],
        ),
    ]
