# Generated by Django 2.1.1 on 2018-11-13 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMgrDept',
            fields=[
                ('Emp_MgrDept_ID', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('Dept_ID', models.PositiveIntegerField(default=0)),
                ('Emp_FullName', models.CharField(max_length=50)),
                ('Dept_Name', models.CharField(max_length=30)),
                ('Manager_FullName', models.CharField(max_length=50)),
                ('Manager_Email_Address', models.EmailField(max_length=70)),
                ('Emp_No_EmpMgrDept', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Emp_No_EmpMgrDept', to='LMS.Employee')),
                ('Manager_Emp_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Emp_ID', to='LMS.Employee')),
            ],
        ),
    ]
